<h1 style="margin-bottom: 75px;font-size:3.5 rem;color:#4c76ce;text-align:center;">
    NumPy Basics: Linear Algebra</h1>
    
<img src="https://raw.githubusercontent.com/lajmcourses/Images/master/numpy.png"
     style="position:absolute;top:5px;left:25px; height:100px;width:auto;margin-bottom:5px;">

# 3. Linear Algebra with NumPy

## 3.1 Vector Norm

Vector norm is a measure of vector distance.

**L1 norm** is also known as Manhattan Distance. Suppose that X is a vector, X = (2, 5), then 

$ L1(X) = || X ||_1 = |2| + |5| = 7 $



In [154]:
# L1 norm

import numpy as np
from numpy.linalg import norm


x = np.array([2, 5])
L1_x = norm(x, 1)

print("x:", x)
print("Norm L1(x):", L1_x)

x: [2 5]
Norm L1(x): 7.0


**L2 norm** is the most popular norm, it is also known as Euclidean norm, it represents the shortest distance from one point to another.
Suppose that X is a vector, X = (3, 4), then 

$ L2(X) = || X ||_2 = \sqrt{3^2 + 4^2} = \sqrt{25} = 5 $

In [155]:
# L2 norm

import numpy as np
from numpy.linalg import norm


x = np.array([3, 4])
L2_x = norm(x, 2)

print("x:", x)
print("Norm L2(x):", L2_x)

x: [3 4]
Norm L2(x): 5.0


**L-infinity norm** returns the largest magnitude among the elements of the vector. Suppose X = (-1, 8, 4, 10] then

$ L\infty(X) = || X ||_\infty = 10 $

In [156]:
# L-infinity norm

import numpy as np
from numpy.linalg import norm

x = np.array([-1, 8, 4, 10])
Linf_x = norm(x, np.inf)
print("Norm L-infinity(x):", Linf_x)

Norm L-infinity(x): 10.0


#### Vector Norm Calculation Example

In [157]:
import numpy as np
from numpy.linalg import norm

v1 = np.array([1, 0, -1, 3, 2])
print("\nVector v1:", v1)

# L2 Norm
norm_l2 = norm(v1, 2)
print("\nNorm L2 of v1:", norm_l2)

# L1 Norm (or Manhattan Distance)
norm_l1 = norm(v1, 1)
print("\nNorm L1 of v1:", norm_l1)

# L-inf Norm
norm_linf = norm(v1, np.inf)
print("\nNorm L-inf of v1:", norm_linf)


Vector v1: [ 1  0 -1  3  2]

Norm L2 of v1: 3.872983346207417

Norm L1 of v1: 7.0

Norm L-inf of v1: 3.0


## 3.2 Scalar Multiplication of Vectors

In [158]:
import numpy as np

# Create vectors
v1 = np.array([1, 2, -3, 2, -1])
v2 = np.array([1, 0, 0, -4, 2])

print("\nVector v1:", v1)
print("\nVector v2:", v2)

# Scalar multiplication of vectors
res = np.dot(v1, v2)
print("\nv1 x v1 = ", res)


Vector v1: [ 1  2 -3  2 -1]

Vector v2: [ 1  0  0 -4  2]

v1 x v1 =  -9


## Exercise 0:

a) Create vector v1 = [1, -4, 10, 11, -5, 0, -2]

b) Create vector v2 = [3, 4, -12, 1, 1, 0, 15]

c) Calculate L2 norm for both of the vectors

d) Calculate the norm L1 for both of the vectors

e) Calculate the norm L-infinity for both of the vectors

f) Find the scalar product of v1 and v2

In [159]:
# Solution to Exercise 0

import numpy as np
from numpy.linalg import norm

# (a)
v1 = np.array([1, -4, 10, 11, -5, 0, -2])
print("\nv1:", v1)

# (b)
v2 = np.array([3, 4, -12, 1, 1, 0, 15])
print("\nv2:", v2)

# (c)

l2_v1 = norm(v1, 2)
print("\nNorm L2 of v1:", l2_v1)

l2_v2 = norm(v2, 2)
print("\nNorm L2 of v2:", l2_v2)

# (d)

l1_v1 = norm(v1, 1)
print("\nNorm L1 of v1:", l1_v1)

l1_v2 = norm(v2, 1)
print("\nNorm L1 of v2:", l1_v2)

# (f)

linf_v1 = norm(v1, np.inf)
print("\nNorm L-infinity of v1:", linf_v1)

linf_v2 = norm(v2, np.inf)
print("\nNorm L-infinity of v2:", linf_v2)

# (f)
sp = np.dot(v1, v2)
print("\nv1 x v2 =", sp)


v1: [ 1 -4 10 11 -5  0 -2]

v2: [  3   4 -12   1   1   0  15]

Norm L2 of v1: 16.34013463836819

Norm L2 of v2: 19.8997487421324

Norm L1 of v1: 33.0

Norm L1 of v2: 36.0

Norm L-infinity of v1: 11.0

Norm L-infinity of v2: 15.0

v1 x v2 = -157


## 3.3 Matrix Norm

The norm of a matrix is a real number which is a measure of the magnitude of the matrix.

**L1 norm of a matrix**

L1 norm of a matrix returns the maximum absolute column sum.

$|| A ||_1 = max_{1<=j<=n} (\sum^n_{i=1}|a_{ij}|)$

In [160]:
# L1 norm of a matrix
from numpy.linalg import norm

A = np.array([
    [1, -7],
    [-2, -3]
])

L1_A = norm(A, 1)
print("A:\n", A)
print("Norm L1 of A:", L1_A)

A:
 [[ 1 -7]
 [-2 -3]]
Norm L1 of A: 10.0


**L2 norm of a matrix (Euclidean norm)**

L2 norm of a matrix is the square root of the sum of all the squares.

$|| A ||_2 = \sqrt{\sum^n_{i=1}\sum^n_{j=1} (a_{ij})^2}$

In [161]:
# L2 norm of a matrix

from numpy.linalg import norm

A = np.array([
    [1, -7],
    [-2, -3]
])

L2_A = norm(A, 'fro')
print("A:\n", A)
print("Norm L2 of A:", L2_A)

A:
 [[ 1 -7]
 [-2 -3]]
Norm L2 of A: 7.937253933193772


**L-infinity norm of a matrix**

L-infinity norm returns the maximum absolute row sum.

$ || A ||\infty = max_{1<=i<=n} (\sum^n_{j=1} |a_{ij}|) $

In [162]:
# L-infinity norm of a matrix

from numpy.linalg import norm

A = np.array([
    [1, -7],
    [-2, -3]
])

Linf_A = norm(A, np.inf)
print("A:\n", A)
print("Norm L-infinity of A:", Linf_A)

A:
 [[ 1 -7]
 [-2 -3]]
Norm L-infinity of A: 8.0


#### Matrix Norm Calculation Example

In [163]:
import numpy as np
from numpy.linalg import norm

m1 = np.array([
    [1, 2, 3, 4, 5],
    [1, 0, 0, -1, 3],
    [-2, 4, 5, 0, 0]
])

print("\nMatrix m1:\n", m1, "\n")


# L2 Norm
norm_l2 = norm(m1, "fro")
print("\nNorm L2 of m1:", norm_l2)

# L1 Norm 
norm_l1 = norm(m1, 1)
print("\nNorm L1 of m1:", norm_l1)

# L-inf Norm
norm_linf = norm(m1, np.inf)
print("\nNorm L-inf of m1:", norm_linf)



Matrix m1:
 [[ 1  2  3  4  5]
 [ 1  0  0 -1  3]
 [-2  4  5  0  0]] 


Norm L2 of m1: 10.535653752852738

Norm L1 of m1: 8.0

Norm L-inf of m1: 15.0


## 3.4 Multiplication of Matrices

In [164]:
import numpy as np 

# Create matrices
m1 = np.array([
    [1, 7], 
    [2, 3], 
    [5, 0]
])

m2 = np.array([
    [2, 6, 3, 1], 
    [1, 2, 3, 4]
])

print("\nMatrix m1:\n", m1)
print("\nMatrix m2:\n", m2)

# Multiplying matrices
m3 = np.dot(m1, m2)
print("\nm3 = m1 x m2:\n", m3)


Matrix m1:
 [[1 7]
 [2 3]
 [5 0]]

Matrix m2:
 [[2 6 3 1]
 [1 2 3 4]]

m3 = m1 x m2:
 [[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


## 3.5 Determinant of a Matrix

In [165]:
import numpy as np
from numpy.linalg import det

# Create matrix
m = np.array([
    [0, 2, 1, 3],
    [3, 2, 8, 1],
    [1, 0, 0, 3],
    [0, 3, 2, 1]
])

print("\nMatrix m:\n", m)

dm = det(m)

print("\nDeterminant of m:", round(dm, 4))



Matrix m:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]

Determinant of m: -38.0


## Exercise 1:


a) Create matrix M = [[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]].

b) Find norms L2, L1, and L-infinity of the matrix

c) Find the determinant of M.

d) Create 4 x 4 identity matrix I

e) Multiplay M by I and show that the result is M

f) Create matrix A = [[1, 2], [-1, 4], [2, 0], [-9, 7]]

g) Multiply matrices: M x A, transposed A x A

In [166]:
## Solution to Exercise 1
import numpy as np
from numpy.linalg import det, norm

# (a)
M = np.array([
    [0, 2, 1, 3],
    [3, 2, 8, 1],
    [1, 0, 0, 3],
    [0, 3, 2, 1]
])

print("\nMatrix M:\n", M)

# (b)
l2_M = norm(M, 2)
print("\nL2 norm of M:", l2_M)

l1_M = norm(M, 1)
print("\nL1 norm of M:", l1_M)

linf_M = norm(M, np.inf)
print("\nL-infinity norm of M:", linf_M)

# (c)
print("\nDeterminant of M:", det(M))

# (d)
I = np.identity(4, dtype=np.int64)
print("\nIdentity matrix 4x4:\n", I)

# (e)
print("\nM x I =\n", np.dot(M, I))

# (f)
A = np.array([
    [1, 2],
    [-1, 4],
    [2, 0],
    [-9, 7]
])
print("\nMatrix A =\n", A)

# (g)
print("\nM x A =", np.dot(M, A))
print("\nA.T x M =", np.dot(A.T, M))


Matrix M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]

L2 norm of M: 9.511345872776696

L1 norm of M: 11.0

L-infinity norm of M: 14.0

Determinant of M: -38.000000000000014

Identity matrix 4x4:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

M x I =
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]

Matrix A =
 [[ 1  2]
 [-1  4]
 [ 2  0]
 [-9  7]]

M x A = [[-27  29]
 [  8  21]
 [-26  23]
 [ -8  19]]

A.T x M = [[ -1 -27 -25  -1]
 [ 12  33  48  17]]


## 3.6 Rank of a Matrix

A rank of an *m x n* matrix *M* is the number of linearly independent columns or rows of A,
and it is denoted as *rank(A)*.

A matrix has full rank if *rank(A) = min(m, n)*.

## 3.7 Inverse Matrix

The inverse of a square matrix M is a matrix of the same size, N, such that, M x N = I.
The inverse of a matrix is analogous to an inverse number: 3 x 1/3 = 1.

A matrix is said to be invertible if it has an inverse.

The inverse of a matrix is unique, that is for an invertible matrix, there is only one inverse for that matrix.

If M is a square matrix, its inverse is denoted as $M^{-1}$

In [167]:
import numpy as np
from numpy.linalg import inv, matrix_rank

# Create matrix
m = np.array([
    [0, 2, 1, 3],
    [3, 2, 8, 1],
    [1, 0, -3, 3],
    [0, 1, 1, 1]
])

print("\nMatrix m:\n", m)

# Check if matrix determinant is not zero
print("\nDeterminant of m:\n", round(det(m), 4))

# Or check if the rank of the matrix is 4
mrank = matrix_rank(m)
print("\nThe rank of A:\n", mrank)

# Matrix m inverse
m_inv = inv(m)
print("\nThe inverse of m:\n", m_inv)


Matrix m:
 [[ 0  2  1  3]
 [ 3  2  8  1]
 [ 1  0 -3  3]
 [ 0  1  1  1]]

Determinant of m:
 -5.0

The rank of A:
 4

The inverse of m:
 [[-3.   0.   1.   6. ]
 [-5.  -0.4  1.2 11.8]
 [ 2.   0.2 -0.6 -4.4]
 [ 3.   0.2 -0.6 -6.4]]


## Exercise 2:

a) Create matrix mp = [[0, 1, 0], [0, 0, 0], [1, 0, 1]]

b) Show that mp has a determinant equal to 0, and hence this matrix has no inverse.

In [168]:
# Solution to Exercise 2

# (a) The matrix has an inverse if the matrix has a full rank (matrix determinant is no 0)

import numpy as np
from numpy.linalg import det, inv, matrix_rank


mp = np.array([
    [0, 1, 0],
    [0, 0, 0],
    [1, 0, 1]
])

print("\nDeterminant of mp:", det(mp))
print("\nRank of mp:", matrix_rank(mp))

is_invertible = matrix_rank(mp) == min(mp.shape)

if is_invertible:
    print("\nMatrix mp is invertible.")
else:
    print(f"\nMatrix mp doesn't have an inverse, it is a singular matrix.")




Determinant of mp: 0.0

Rank of mp: 2

Matrix mp doesn't have an inverse, it is a singular matrix.


## Exercise 3:

a) Create matrix A = [[1, 0, 1], [-4, 3, 0], [1, 0, -2]]

b) Compute the rank of the matrix A

c) Find the determinant of A

d) Find the inverse of A

e) Multiply A by the inverse of A, and explain the result

In [169]:
# Solution to Exercise 3

import numpy as np
from numpy.linalg import det, inv, matrix_rank


# (a)
A = np.array([
    [1, 0, 1],
    [-4, 3, 0],
    [1, 0, -2]
])

print("\nMatrix A:\n", A)

# (b)
print("\nRank of A:", matrix_rank(A))
print("A has a full rank:", matrix_rank(A) == min(A.shape))

# (c)
print("\nDeterminant of A:", det(A))

# (d)
print("\nInverse of A:\n", inv(A))

# (e): when we multiply a matrix by its inverse we get an identity matrix
print("\nA x inv(A) =\n", np.dot(A, inv(A)))



Matrix A:
 [[ 1  0  1]
 [-4  3  0]
 [ 1  0 -2]]

Rank of A: 3
A has a full rank: True

Determinant of A: -8.999999999999998

Inverse of A:
 [[ 0.66666667 -0.          0.33333333]
 [ 0.88888889  0.33333333  0.44444444]
 [ 0.33333333 -0.         -0.33333333]]

A x inv(A) =
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 1.11022302e-16  0.00000000e+00  1.00000000e+00]]


## 3.8 Solving Linear Equations Systems

A linear equation is an equality of the form

$$ \sum_{i=1}^{n} a_i x_i = y $$


A system of linear equations is a set of linear equations that share the same variables, for example:

$$ a_{11} x_1 + a_{12} x_2 + a_{13} x_3 = y_1 $$
$$ a_{21} x_1 + a_{22} x_2 + a_{23} x_3 = y_2 $$
$$ a_{31} x_1 + a_{32} x_2 + a_{33} x_3 = y_3 $$

The system of linear equations can be writtend in the matrix form:

$$ A x = y $$

where

$ A = 
\begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33} \\
\end{bmatrix}
$

$ x = [x_1, x_2, x_3] $

$ y = [y_1, y_2, y_3] $

## Exercise 4

Put the equations system below into matrix form:

$$
\begin {cases}
  4x + 3y - 5z = 2 \\
  -2x - 4y + 5z = 5 \\
  7x + 8y      = -3 \\
  x +  2z      = 1 \\
  9x + y - 6z   = 6 \\ 
\end {cases}
$$


In [170]:
# Solution to Exercise 4

# X = [x, y, z] - vector of unknown variables

# A: coefficient matrix
A = np.array([
    [4, 3, -5],
    [-2, -4, 5],
    [1, 0, 2],
    [9, 1, -6]
])

print("\nMatrix A:\n", A)

Y = np.array([2, 5, -3, 1, 6])
print("\nVector y:", Y)


Matrix A:
 [[ 4  3 -5]
 [-2 -4  5]
 [ 1  0  2]
 [ 9  1 -6]]

Vector y: [ 2  5 -3  1  6]


## 3.9 Solutions to Systems of Linear Equations

Consider a system of linear equations in matrix form, *Ax = y*, where *A* is an *m × n* matrix. 
Recall that this means there are *m* equations and *n* unknowns in our system. 
A solution to this system of linear equations is a vector *x* of size *n*. There are three possibilities:

1) The linear system has no solutions for *x*.

2) There is one unique solution *x* that solves the system of linear equations.

3) There are infinitely many solutions for *x* solving the linear equations system.


**Case 1: There is no solutions for x**

If *rank([A, y]) = rank(A) + 1* then y is linearly independent from the columns of A. 
Therefore, because *y* is not in the range of *A*, by definition there cannot
be an *x* that satisfies the equation. Thus, comparing *rank([A, y])* and *rank(A)* provides an easy
way to check if there are no solutions to a system of linear equations.


**Case 2: There is unique solution for x**

If *rank([A, y]) = rank(A)*, then y can be written as a linear combination of the columns of *A*, 
and there is at least one solution for the matrix equation. For there to be only one solution, 
*rank(A) = n* must also be true. In other words, the number of equations must be exactly equal to the number of unknowns.


**Case 3: There are infinitely many solutions for x**

If *rank([A, y]) = rank(A)*, then *y* is in the range of *A*, and there is at least one solution for the matrix equation; however, if *rank(A) < n*, then there are infinitely many solutions. 


## Exercise 5

How many solutions does the system have:
    
a) 
$$
\begin {cases}
 4x + 3y - 5z = 2   \\
-2x - 4y + 5z = 5  \\
 7x + 8y      = -3 \\
  x +  2z      = 1 \\
 9x + y - 6z   = 6
\end {cases}
$$

b) 
$$
\begin {cases}
 x_1 +2x_2 + x_3 + 3x_4 = 1 \\
 3x_1 + 2x_2 + 8x_3 + x_4 = -7 \\
 x_1 + 3x_4 = 0 \\
 4x_2 + 2x_3 + 6x_4 = 15
\end {cases}
$$

c) 

$$
\begin {cases}
 3x_1 - x_2 = 2 \\
 -6x_1 + 2x_2 = -4 \\
 x_1 + 12x_2 - 7x_3 = 54
\end {cases}
$$


In [171]:
# Solution to Exercise 5
import numpy as np
from numpy.linalg import matrix_rank

# (a)

A = np.array([
    [4, 3, -5],
    [-2, -4, 5],
    [7, 8, 0],
    [1, 0, 2],
    [9, 1, -6]
])

print("\nMatrix A:\n", A)

y = np.array([2, 5, -3, 1, 6])

Ay = np.append(A, y.reshape(5, 1), axis=1)
print("Extended matrix Ay:\n", Ay)

rank_A = matrix_rank(A)
print("Rank of A:", rank_A)

rank_Ay = matrix_rank(Ay)
print("Rank of Ay:", rank_Ay)

# Answer: equation (a) has no solution, because rank(Ay) = rank(A) + 1

# (b)

A = np.array([
    [1, 2, 1, 3],
    [3, 2, 8, 1], 
    [1, 0, 0, 3],
    [0, 4, 2, 6]
])

print("\nMatrix A:\n", A)

y = np.array([1, -7, 0, 15])

Ay = np.append(A, y.reshape(4, 1), axis=1)
print("Extended matrix Ay:\n", Ay)

rank_A = matrix_rank(A)
print("Rank of A:", rank_A)

rank_Ay = matrix_rank(Ay)
print("Rank of Ay:", rank_Ay)

print("Number of equations n:", len(A))

# Answer: equation (b) has a unique solution, because rank(Ay) = rank(A) = n

# (c)

A = np.array([
    [3, -1, 0, 3], 
    [-6, 2, 0, -6],
    [1, 12, -7, 0]
])

print("\nMatrix A:\n", A)

y = np.array([2, -4, 54])

Ay = np.append(A, y.reshape(3, 1), axis=1)
print("Extended matrix Ay:\n", Ay)

rank_A = matrix_rank(A)
print("Rank of A:", rank_A)

rank_Ay = matrix_rank(Ay)
print("Rank of Ay:", rank_Ay)

print("Number of equations n:", len(A))

# Answer: equation (c) has infinitely many solution, because rank(Ay) = rank(A) < n


Matrix A:
 [[ 4  3 -5]
 [-2 -4  5]
 [ 7  8  0]
 [ 1  0  2]
 [ 9  1 -6]]
Extended matrix Ay:
 [[ 4  3 -5  2]
 [-2 -4  5  5]
 [ 7  8  0 -3]
 [ 1  0  2  1]
 [ 9  1 -6  6]]
Rank of A: 3
Rank of Ay: 4

Matrix A:
 [[1 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 4 2 6]]
Extended matrix Ay:
 [[ 1  2  1  3  1]
 [ 3  2  8  1 -7]
 [ 1  0  0  3  0]
 [ 0  4  2  6 15]]
Rank of A: 4
Rank of Ay: 4
Number of equations n: 4

Matrix A:
 [[ 3 -1  0  3]
 [-6  2  0 -6]
 [ 1 12 -7  0]]
Extended matrix Ay:
 [[ 3 -1  0  3  2]
 [-6  2  0 -6 -4]
 [ 1 12 -7  0 54]]
Rank of A: 2
Rank of Ay: 2
Number of equations n: 3


## 3.10 Solving Linear Equations Systems with Numpy

Let's solve the linear system from the exercise 5:

$$ 
\begin {cases}
 4x + 3y - 5z = 2   \\
-x - 2y + 3z = 3  \\
 8x + 2y - 2z = 3 \\
\end {cases}
$$

The number of unknowns *n=3*. The number of equations *m=3*.

The first step is to write down the equation in the matrix form.

The next step is to determine if the equation has a solution. (We need to find the ranks of the matrices *A* and *[A,y]*)

Finally, if the solution exist we need to find it.

In [172]:
# Solving Linear Equations System

import numpy as np
from numpy.linalg import solve, matrix_rank

# Matrix A

A = np.array([
    [4, 3, -5],
    [-1, -2, 3],
    [8, 2, -2], 
])
print("\nMatrix A:\n", A)

arank = matrix_rank(A)
print("\nRank of A:", arank)

y = np.array([2, 3, 3])
print("\nVector y:", y)

# Matrix [A, y]
Ay = np.append(A, y.reshape(len(y), 1), axis=1)

print("\nMatrix [A,y]:\n", Ay)

ayrank = matrix_rank(Ay)
print("\nThe rank of Ay:", ayrank)

if arank == ayrank and arank == len(A):
    print("\nConclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution.")

    # Solving the linear equations system
    x = solve(A, y)
    
    print("\nSolution to the system: x:", x)
    
    # Testing the solution, Ax should be equal to y
    Ax = np.dot(A, x)
    print("\nTest: A * x =", Ax)


Matrix A:
 [[ 4  3 -5]
 [-1 -2  3]
 [ 8  2 -2]]

Rank of A: 3

Vector y: [2 3 3]

Matrix [A,y]:
 [[ 4  3 -5  2]
 [-1 -2  3  3]
 [ 8  2 -2  3]]

The rank of Ay: 3

Conclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution.

Solution to the system: x: [ 1.58333333 -9.91666667 -5.08333333]

Test: A * x = [2. 3. 3.]


## Exercise 6

a) Show that the system has a unique solution:
    
$$
\begin {cases}
4x_1 + 3x_2 - 5x_3 = 2 \\
-2x_1 - 4x_2 + 5x_3 = 5 \\
8x_1 + 8x_2 = -3
\end {cases}
$$

b) Solve the linear equations system

In [173]:
# Solution to Exercise 6

import numpy as np
from numpy.linalg import solve, matrix_rank

# Matrix A

A = np.array([
    [4, 3, -5],
    [-2, -4, 5],
    [8, 8, 0], 
])
print("\nMatrix A:\n", A)

arank = matrix_rank(A)
print("\nRank of A:", arank)

y = np.array([2, 5, -3])
print("\nVector y:", y)

# Matrix [A, y]
Ay = np.append(A, y.reshape(len(y), 1), axis=1)

print("\nMatrix [A,y]:\n", Ay)

ayrank = matrix_rank(Ay)
print("\nThe rank of Ay:", ayrank)

if arank == ayrank and arank == len(A):
    print("\nConclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution.")

    # Solving the linear equations system
    x = solve(A, y)
    
    print("\nSolution to the system: x:", x)
    
    # Testing the solution, Ax should be equal to y
    Ax = np.dot(A, x)
    print("\nTest: A * x =", Ax)



Matrix A:
 [[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]]

Rank of A: 3

Vector y: [ 2  5 -3]

Matrix [A,y]:
 [[ 4  3 -5  2]
 [-2 -4  5  5]
 [ 8  8  0 -3]]

The rank of Ay: 3

Conclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution.

Solution to the system: x: [ 2.20833333 -2.58333333 -0.18333333]

Test: A * x = [ 2.  5. -3.]


## Exercise 7

a) Show that the system has a unique solution:

$$
\begin {cases}
    3x_1 - x_2 + 4x_3 = 2 \\
    17x_1 + 2x_2 + x_3 = 14 \\
    x_1 + 12x_2 + 7x_3 = 54 \\
\end {cases}
$$

b) Solve the linear equations system

In [174]:
import numpy as np
from numpy.linalg import solve, matrix_rank

# Matrix A

A = np.array([
    [3, -1, 4],
    [17, 2, 1],
    [1, 12, 7], 
])
print("\nMatrix A:\n", A)

arank = matrix_rank(A)
print("\nRank of A:", arank)

y = np.array([2, 14, 54])
print("\nVector y:", y)

# Matrix [A, y]
Ay = np.append(A, y.reshape(len(y), 1), axis=1)

print("\nMatrix [A,y]:\n", Ay)

ayrank = matrix_rank(Ay)
print("\nThe rank of Ay:", ayrank)

if arank == ayrank and arank == len(A):
    print("\nConclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution.")

    # Solving the linear equations system
    x = solve(A, y)
    
    print("\nSolution to the system: x:", x)
    
    # Testing the solution, Ax should be equal to y
    Ax = np.dot(A, x)
    print("\nTest: A * x =", Ax)


Matrix A:
 [[ 3 -1  4]
 [17  2  1]
 [ 1 12  7]]

Rank of A: 3

Vector y: [ 2 14 54]

Matrix [A,y]:
 [[ 3 -1  4  2]
 [17  2  1 14]
 [ 1 12  7 54]]

The rank of Ay: 3

Conclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution.

Solution to the system: x: [0.30901288 3.76824034 1.21030043]

Test: A * x = [ 2. 14. 54.]
